### ISSUE TITLE
Hello~~Is there a paper for this GAN model? Or just an experiment?Tank you very muck :)

### ISSUE THREAD

**Issue by 22w2w2** [jaesik817/SequentialData-GAN#4]

**Comment by jsikyoon** [comment]
no, this is just experiment.

**Comment by 22w2w2** [comment]
Thank you for your answer, I would also like to ask a question that may seem simple to you. When dealing with D's LSTM output, why only the last output is used to calculate LOSS? Very much looking forward to your answer!

**Comment by jsikyoon** [comment]
Hi,

sorry for late response.

my implementation is to simplify the sequential GAN with one-to-many modeling (generator) and many-to-one modeling (discriminator).

many-to-one modeling is not essential in my thinking, thus, you can enjoy other modeling for that.

Thanks.

BRs, Jaesik Yoon.
